version: "3.7"

services:
  nextjs:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - '3000:3000'
  strapi:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - '1337:1337'