version: "3.7"

services:
  nextjs:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  strapi:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '1337:1337'
