version: "3.7"

services:
  nextjs:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./client:/app
  strapi:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - '1337:1337'
    volumes:
      - /app/node_modules
      - ./server:/app