version: "3.7"

services:
  nextjs:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    build:
      dockerfile: Dockerfile
      context: client/config/nginx/dev
    ports:
      - '80:80'
    volumes:
      - ./client/config/nginx/dev/conf.d:/etc/nginx/conf.d
    links:
      - nextjs
    restart: always
